# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browse_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Browser2(object):
    def setupUi(self, Browser2):
        Browser2.setObjectName("Browser2")
        Browser2.resize(272, 135)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Browser2.setWindowIcon(icon)
        Browser2.setStyleSheet("background-color: #929294;")
        self.browse_file_2 = QtWidgets.QPushButton(Browser2)
        self.browse_file_2.setGeometry(QtCore.QRect(170, 70, 91, 21))
        self.browse_file_2.setStyleSheet("QPushButton {\n"
"    background-color: #ceced9;\n"
"    font: 8pt \"Poor Richard\";\n"
"    border: 1px solid gray;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #acadb0;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #d4d4d6;\n"
"} \n"
"")
        self.browse_file_2.setObjectName("browse_file_2")
        self.browse_line_2 = QtWidgets.QLineEdit(Browser2)
        self.browse_line_2.setGeometry(QtCore.QRect(20, 70, 141, 21))
        self.browse_line_2.setStyleSheet("background-color:#fff;")
        self.browse_line_2.setObjectName("browse_line_2")

        self.retranslateUi(Browser2)
        QtCore.QMetaObject.connectSlotsByName(Browser2)

    def retranslateUi(self, Browser2):
        _translate = QtCore.QCoreApplication.translate
        Browser2.setWindowTitle(_translate("Browser2", "Browse"))
        self.browse_file_2.setText(_translate("Browser2", "Обзор"))



