# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encrypted.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EncryptedFile(object):
	def setupUi(self, EncryptedFile):
		EncryptedFile.setObjectName("EncryptedFile")
		EncryptedFile.resize(315, 122)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("../icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		EncryptedFile.setWindowIcon(icon)
		EncryptedFile.setStyleSheet("background-color: #929294;")
		self.label = QtWidgets.QLabel(EncryptedFile)
		self.label.setGeometry(QtCore.QRect(60, 10, 201, 51))
		self.label.setStyleSheet("QLabel {\n"
"color: #fff;\n"
"font: 17pt \"Mongolian Baiti\";\n"
"}")
		self.label.setObjectName("label")
		self.Enc_File = QtWidgets.QPushButton(EncryptedFile)
		self.Enc_File.setGeometry(QtCore.QRect(110, 70, 91, 31))
		self.Enc_File.setStyleSheet("QPushButton {\n"
"    background-color: #ceced9;\n"
"    font: 8pt \"Poor Richard\";\n"
"    border: 1px solid gray;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #acadb0;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #d4d4d6;\n"
"} \n"
"")
		self.Enc_File.setObjectName("Enc_File")

		self.retranslateUi(EncryptedFile)
		QtCore.QMetaObject.connectSlotsByName(EncryptedFile)

	def retranslateUi(self, EncryptedFile):
		_translate = QtCore.QCoreApplication.translate
		EncryptedFile.setWindowTitle(_translate("EncryptedFile", "Encrypted"))
		self.label.setText(_translate("EncryptedFile", "Файл зашифрован"))
		self.Enc_File.setText(_translate("EncryptedFile", "ОК"))



